### ISSUE TITLE
Add “-vanity” to arxiv.org URLs to convert them to web pages

### ISSUE THREAD

**Issue by adhsu** [arxiv-vanity/arxiv-vanity#82]
It would be very cool if I could just take a link like:
https://arxiv.org/pdf/1707.01836.pdf

And append "-vanity" to form: https://arxiv-vanity.org/pdf/1707.01836.pdf

arxiv-vanity.org is available for $13 on namecheap.com and this would definitely help more people remember to use it, imo.

**Comment by bfirsh** [comment]
Great idea. Thank you!

**Comment by bfirsh** [comment]
We could start by adding support to the current app - a 404 handler that sees if the URL looks a bit like a Arxiv URL. I wonder if this might bite us in the future if we want to add more routes though.

**Comment by infogulch** [comment]
You could add this feature to specific routes on a case-by-case basis, right? E.g. just `/pdf/`, `/abs/`, and `/format/` routes at first. I doubt arxiv.org will be overhauling their routing any time soon.

I think this feature would be a major boon. Just now I opened up a pdf and thought to myself "wait isn't there that arxiv-vanity thing? I wonder if...." and I added "-vanity" to the url to see if it would work, but alas.

Another option would be to purchase arxiv-vanity.org and reserve it to only do redirects. E.g. any url that hits arxiv-vanity.org that matches a paper in the arxiv.org route format just redirects to arxiv-vanity.*com*/papers/id...

**Comment by infogulch** [comment]
So, uh... I didn't feel like waiting. 🤷‍♂️

I purchased `arxiv-vanity.org` (it wasn't yet!) and set up a 10-line http server that fixes up `/pdf/`, `/abs/`, and `/format/` into `/papers/`, but otherwise just 302-redirects everything to www.arxiv-vanity.com. (I don't plan to do anything else with the domain.)

So, **right now**, you can open any paper on arxiv.org, edit the url to add `-vanity` to the domain and it takes you to the paper on www.arxiv-vanity.com. Yay! 😄

**Comment by bfirsh** [comment]
@infogulch Nice! Thank you!

Would you mind sharing the code? It'd probably be more resilient if we made it part of the same app as arxiv-vanity.com.

**Comment by infogulch** [comment]
Sure! There's no "application" running in the traditional sense, just an http server with some rules. Specifically [Caddy](https://caddyserver.com/), which does completely automatic https via Lets Encrypt which is something I wanted for security and low maintenance.

Here's the Caddyfile:

```
www.arxiv-vanity.org, arxiv-vanity.org {
        rewrite /abs {
                r (.*)
                to /papers{1}
        }
        rewrite /pdf {
                r (.*)(\.pdf)
                to /papers{1}
        }
        rewrite /format {
                r (.*)
                to /papers{1}
        }
        redir / https://www.arxiv-vanity.com{rewrite_uri} 302
}
```

Pretty simple. I had to strip off `.pdf` but otherwise that's it. I did a 302 redirect in case you guys wanted to do something with it in the future a bunch of clients wouldn't have cached 301 redirects in random paths, or if I needed to fix a rule.

**Comment by jkukul** [comment]
@infogulch Looks like your redirect server is no longer online.

How about supporting all arXiv-like urls inside arxiv-vanity.com app (something like https://github.com/arxiv-vanity/arxiv-vanity/pull/375) + setting a CNAME for arxiv-vanity.org which points to arxiv-vanity.com?

**Comment by bfirsh** [comment]
#375 added the arxiv-vanity.com side stuff that is needed. I have set up a redirect from .org to .com, which is currently waiting on DNS propagating I think.

Thanks @infogulch and @jkukul for making this happen!

**Comment by bfirsh** [comment]
https://arxiv-vanity.org/abs/1605.07683 :tada:

**Comment by infogulch** [comment]
Excellent, I'm glad you were able to integrate it!  I think this is a fantastic feature.
